cesi-tp-jey-front/Models/DTO/PaymentDTO.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace cesi_tp_jey_front.DTO 
{

    public class PaymentDTO
    {

        private int _id;
        private string _customerName;
        private float _amount;
        private String _creationDate;

        // Getters and Setters

        public int id
        {
            get { return _id; }
            set { _id = value; }
        }

        public string customerName
        {
            get { return _customerName; }
            set { _customerName = value; }
        }

        [Range(0, Int32.MaxValue, ErrorMessage = "Value should be greater than or equal to 1")]
        public float amount
        {
            get { return _amount; }
            set { _amount = value; }
        }

        public String creationDate
        {
            get { return _creationDate; }
            set { _creationDate = value; }
        }

    }

}

cesi-tp-jey-front/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace cesi_tp_jey_front.Models
{

    public class Payment
    {

        private int _id;
        private string _customerName;
        private float _amount;
        private string _creationDate;

        // Getters and Setters

        public int id
        {
            get { return _id; }
            set { _id = value; }
        }

        [Required]
        public string customerName
        {
            get { return _customerName; }
            set { _customerName = value; }
        }

        [Range(0, Int32.MaxValue, ErrorMessage = "Value should be greater than or equal to 0")]
        public float amount
        {
            get { return _amount; }
            set { _amount = value; }
        }

        public string creationDate
        {
            get { return _creationDate; }
            set { _creationDate = value; }
        }

    }

}

cesi-tp-jey-front/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cesi_tp_jey_front.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
        
    }

}

cesi-tp-jey-front/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Web.Mvc;
using cesi_tp_jey_front.Services;
using Newtonsoft.Json;
using cesi_tp_jey_front.Models;
using cesi_tp_jey_front.DTO;

namespace cesi_tp_jey_front.Controllers
{
    
    /// <summary>
    /// This controller redirect the paths towards services and views for payments.
    /// </summary>
    public class PaymentController : Controller
    {
        
        /// <summary>
        /// This method initialize WebClient for sending resources with URI to service.
        /// </summary>
        /// <returns>Payments list</returns>
        [HttpGet]
        public ActionResult List()
        {
            
            using (var client = new WebClient())
            {
                // TODO : Implement DI.
                PaymentServiceImpl paymentService = new PaymentServiceImpl();               
                return View("List", paymentService.GetAll(client));
            }
        }
   
        [HttpGet]
        public ActionResult Create()
        {            
                return View("Create");
        }

        /// <summary>
        /// Add the date to the resource. Verify and send it to paymentService
        /// </summary>
        /// <param name="payment">A new payment.</param>
        /// <returns>If success redirect to list
        /// If error redirect to view with error message</returns>
        [HttpPost]
        public ActionResult Create(Payment payment)
        {
            // if Model is valid redirect a view with a payments list
            // else return payment view with an error message
            if (ModelState.IsValid)
            {
                payment.creationDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");
                PaymentServiceImpl paymentService = new PaymentServiceImpl();
                
                if (paymentService.Create(payment))
                {
                    return RedirectToAction("List");
                }
                else
                {
                    ViewData["error"] = "Amount can't be negative value";
                    return View(payment);
                }                
            }
            else
            {
                return View(payment);
            }

        }      

    }

}

cesi-tp-jey-front/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
    ViewBag.Enzo = "There is Enzo Grassi.";
    ViewBag.Jonathan = "There is Jonathan Varela .";
    ViewBag.Yusuf = "There is Yusuf Yildirim.";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Enzo</h3>



<h3>@ViewBag.Jonathan</h3>



<h3>@ViewBag.Yusuf</h3>

cesi-tp-jey-front/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="container">
    <p>Welcome on JEY application</p>
</div>

cesi-tp-jey-front/Views/Payment/Create.cshtml
@model cesi_tp_jey_front.Models.Payment

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.customerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.customerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.customerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

cesi-tp-jey-front/Views/Payment/List.cshtml
@model IEnumerable<cesi_tp_jey_front.Models.Payment>

@{
    ViewBag.Title = "Payments";
}

<h2>Payments</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.customerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.creationDate)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.customerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.creationDate)
        </td>
 
    </tr>
}

</table>

cesi-tp-jey-front/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Jey Compagnie", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Payments", "List", "Payment")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>